---
title: "Stats506_Project"
author: "Heleyna Tucker"
format: html
editor: visual
---

# Project - Light data in buildings

### Load in data:

```{r}
library(tidyverse)
energy <- read_csv('/Users/19892/Downloads/cbecs2018_final_public.csv')
engery_comp <- energy[c("LTZHRP", "LTOHRP", "LTNHRP", "FLUORP", "CFLRP", "BULBP", "HALOP", "HIDP", "LEDP", "LEDP", "OTLTP"),]
```

Read in File below and get necessary data:

```{r}
energy <- read_csv('/Users/19892/Downloads/cbecs2018_final_public.csv')
energy_comp <- energy[c("PUBID","LTZHRP", "LTOHRP", "LTNHRP", "FLUORP", "CFLRP", "BULBP", "HALOP", "HIDP", "LEDP", "OTLTP")]
head(energy_comp)
```

```{r}
#Rename columns to be easily identifiable
colnames(energy_comp) <- c("buildingID", "pLitNoHours", "pLitOpen", "pLitOffHours", "pFluor", "pCompFluor", "pIncandes", "pHalogen", "pHID", "pLED", "pOther")
head(energy_comp)
```

For the sake of data analysis, I will assume that the NA values are 0 percentage values:

```{r}
energy_comp[is.na(energy_comp)] <- 0
head(energy_comp)
```

Look at a Summary:

```{r}
summary(energy_comp)
```

```{r}
k <- 3
kmeans_results <- kmeans(energy_comp, centers = k, nstart = 20)
```

Examine results of the clustering:

```{r}
#Cluster centers:
kmeans_results$centers

#Cluster assignment for each building:
cluster_assignment <- kmeans_results$cluster
```

Visualization:

```{r}
library(GGally)

ggplot(data.frame(energy_comp, cluster = factor(cluster_assignment)), aes(color = cluster)) +
  ggpairs(mapping = aes(color = cluster))
```
